<a href="https://colab.research.google.com/github/Ainadri-Mandal/DS_Practice/blob/main/Array_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array Sorting

In [61]:
import numpy as np

In [62]:
arr = np.array([[6,7,5,3,9],[2,4,6,8,1],[1,3,5,7,9]])
arr

array([[6, 7, 5, 3, 9],
       [2, 4, 6, 8, 1],
       [1, 3, 5, 7, 9]])

In [63]:
np.sort(arr, axis = 1, kind = 'mergesort')  #axis = 1 means it is done row wise

array([[3, 5, 6, 7, 9],
       [1, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [64]:
np.sort(arr, axis = 0, kind = 'mergesort')   #axis = 0 means it is done column wise

array([[1, 3, 5, 3, 1],
       [2, 4, 5, 7, 9],
       [6, 7, 6, 8, 9]])

In [65]:
np.sort(arr, kind = 'mergesort')  # by default sorting is done row wise (axis = 0)

array([[3, 5, 6, 7, 9],
       [1, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [66]:
# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)
print ("Along first axis : \n", arr1)


# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)
print ("\nAlong last axis : \n", arr2)


a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along last axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [67]:
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
print("Using Merge Sort: ",np.sort(arr , axis = 0, kind = 'mergesort'))
print()
print("Using Quick Sort: ",np.sort(arr , axis = 1, kind = 'quicksort'))
print()
print("Using Heap Sort: ",np.sort(arr , kind = 'heapsort'))

Using Merge Sort:  [[5 2 2 3 1]
 [7 3 8 6 4]
 [7 4 9 8 6]]

Using Quick Sort:  [[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]

Using Heap Sort:  [[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]


# Array Merging

In [68]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[8,7,6,5], [4,3,2,1]])

In [69]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

## Concatenating the arrays

In [71]:
print("Stacking arr1 on arr2 vertically: ",np.vstack((arr1,arr2))) #used to stack arrays vertically, stacking rows on top of each other.
print("Stacking arr2 on arr1 vertically: ",np.vstack((arr2,arr1)))
print("Stacking arr1 on arr1 vertically: ",np.vstack((arr1,arr1)))

Stacking arr1 on arr2 vertically:  [[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]
Stacking arr2 on arr1 vertically:  [[8 7 6 5]
 [4 3 2 1]
 [1 2 3 4]
 [5 6 7 8]]
Stacking arr1 on arr1 vertically:  [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [72]:
np.vstack((arr2,arr1))

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
print("Stacking arr1 on arr2 vertically: ",np.hstack((arr1,arr2)))

Stacking arr1 on arr2 vertically:  [[1 2 3 4 8 7 6 5]
 [5 6 7 8 4 3 2 1]]


In [74]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

## Using Concatenate function

In [75]:
arr = np.concatenate((arr1,arr2), axis = 0)


In [76]:
np.concatenate((arr1,arr2), axis = 1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [77]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [78]:
np.hsplit(arr, 2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [79]:
np.vsplit(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]

In [80]:
arr = np.arange(4.0).reshape(2,2)
result = np.hsplit(arr,2)

print(result)

[array([[0.],
       [2.]]), array([[1.],
       [3.]])]


#Array Slicing

In [81]:
arr = np.array([1,2,3,4,5,6,7,8])

In [82]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

### Accesing elements in array

In [83]:
print(int(arr[0]))
print(int(arr[1]))
print(int(arr[-1]))

1
2
8


In [84]:
arr[ : ]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
arr[3:]

array([4, 5, 6, 7, 8])

In [86]:
arr[:-3]

array([1, 2, 3, 4, 5])

In [87]:
arr[3:-3]

array([4, 5])

## Accessing elements in 2D array

In [88]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])


In [89]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [90]:
arr1[ : , :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [91]:
print('Only the 1st row: ')
arr1[ : 1, : ]

Only the 1st row: 


array([[1, 2, 3, 4]])

In [92]:
print('Only the 1st 2 rows: ')
arr1[ : 2, : ]

Only the 1st 2 rows: 


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [93]:
print('All rows except the 1st row: ')
arr1[1 : , : ]

All rows except the 1st row: 


array([[5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [94]:
print('Only the 1st 2 columns: ')
arr1[ : , : 2]

Only the 1st 2 columns: 


array([[1, 2],
       [5, 6],
       [8, 7],
       [4, 3]])

In [95]:
arr1[1: , 1:2]

array([[6],
       [7],
       [3]])

In [96]:
arr1[1: , 1]

array([6, 7, 3])

In [97]:
print(int(arr1[1,1]))
print(int(arr1[2,3]))

6
5


In [98]:
arr1[1: , 1:]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

# Automating using Numpy

In [99]:
lst =[1,2,3,4,5,6,7,8,9,10]

In [110]:
# how many elements in the list are more than 5
count = 0

for i in lst:
  if (i>5):
    print(i)
    count += 1
print("No. of elements are: ",count)

6
7
8
9
10
No. of elements are:  5


In [111]:
# same using Numpy arrays

lst = np.array([1,2,3,4,5,6,7,8,9,10])

In [112]:
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
lst[lst > 5]

array([ 6,  7,  8,  9, 10])

In [118]:
print('No. of elements greater than 5 are: ',len(lst[lst > 5]))
print("The elements greater than 5 are: ",lst[lst > 5])

No. of elements greater than 5 are:  5
The elements greater than 5 are:  [ 6  7  8  9 10]


In [120]:
# elements divisible by 3
lst[lst % 3 == 0]

array([3, 6, 9])