<a href="https://colab.research.google.com/github/Ainadri-Mandal/DS_Practice/blob/main/Array_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array Sorting

In [1]:
import numpy as np

In [3]:
arr = np.array([[6,7,5,3,9],[2,4,6,8,1],[1,3,5,7,9]])
arr

array([[6, 7, 5, 3, 9],
       [2, 4, 6, 8, 1],
       [1, 3, 5, 7, 9]])

In [6]:
np.sort(arr, axis = 1, kind = 'mergesort')  #axis = 1 means it is done row wise

array([[3, 5, 6, 7, 9],
       [1, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [7]:
np.sort(arr, axis = 0, kind = 'mergesort')   #axis = 0 means it is done column wise

array([[1, 3, 5, 3, 1],
       [2, 4, 5, 7, 9],
       [6, 7, 6, 8, 9]])

In [10]:
np.sort(arr, kind = 'mergesort')  # by default sorting is done row wise (axis = 0)

array([[3, 5, 6, 7, 9],
       [1, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])