<a href="https://colab.research.google.com/github/Ainadri-Mandal/DS_Practice/blob/main/Array_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array Sorting

In [1]:
import numpy as np

In [2]:
arr = np.array([[6,7,5,3,9],[2,4,6,8,1],[1,3,5,7,9]])
arr

array([[6, 7, 5, 3, 9],
       [2, 4, 6, 8, 1],
       [1, 3, 5, 7, 9]])

In [3]:
np.sort(arr, axis = 1, kind = 'mergesort')  #axis = 1 means it is done row wise

array([[3, 5, 6, 7, 9],
       [1, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [4]:
np.sort(arr, axis = 0, kind = 'mergesort')   #axis = 0 means it is done column wise

array([[1, 3, 5, 3, 1],
       [2, 4, 5, 7, 9],
       [6, 7, 6, 8, 9]])

In [5]:
np.sort(arr, kind = 'mergesort')  # by default sorting is done row wise (axis = 0)

array([[3, 5, 6, 7, 9],
       [1, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [6]:
# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)
print ("Along first axis : \n", arr1)


# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)
print ("\nAlong last axis : \n", arr2)


a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along last axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [7]:
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
print("Using Merge Sort: ",np.sort(arr , axis = 0, kind = 'mergesort'))
print()
print("Using Quick Sort: ",np.sort(arr , axis = 1, kind = 'quicksort'))
print()
print("Using Heap Sort: ",np.sort(arr , kind = 'heapsort'))

Using Merge Sort:  [[5 2 2 3 1]
 [7 3 8 6 4]
 [7 4 9 8 6]]

Using Quick Sort:  [[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]

Using Heap Sort:  [[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]


# Array Merging

In [8]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[8,7,6,5], [4,3,2,1]])

In [9]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

## Concatenating the arrays

In [11]:
print("Stacking arr1 on arr2 vertically: ",np.vstack((arr1,arr2))) #used to stack arrays vertically, stacking rows on top of each other.
print("Stacking arr2 on arr1 vertically: ",np.vstack((arr2,arr1)))
print("Stacking arr1 on arr1 vertically: ",np.vstack((arr1,arr1)))

Stacking arr1 on arr2 vertically:  [[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]
Stacking arr2 on arr1 vertically:  [[8 7 6 5]
 [4 3 2 1]
 [1 2 3 4]
 [5 6 7 8]]
Stacking arr1 on arr1 vertically:  [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [12]:
np.vstack((arr2,arr1))

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
print("Stacking arr1 on arr2 vertically: ",np.hstack((arr1,arr2)))

Stacking arr1 on arr2 vertically:  [[1 2 3 4 8 7 6 5]
 [5 6 7 8 4 3 2 1]]


In [14]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

## Using Concatenate function

In [15]:
arr = np.concatenate((arr1,arr2), axis = 0)


In [16]:
np.concatenate((arr1,arr2), axis = 1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [17]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [18]:
np.hsplit(arr, 2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [19]:
np.vsplit(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]

In [20]:
arr = np.arange(4.0).reshape(2,2)
result = np.hsplit(arr,2)

print(result)

[array([[0.],
       [2.]]), array([[1.],
       [3.]])]


#Array Slicing