In [1]:
import numpy as np

# 1. Converting a List into np Array

In [2]:
lst = [1,2,3,4]
print(type(lst))
arr = np.array(lst)
print(type(arr))
arr = np.array(lst, ndmin = 2)   #ndmin states how many dimensionsion we want in array
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3 4]]


In [3]:
arr = np.array(lst, ndmin = 1)   #ndmin states how many dimensionsion we want in array
arr

array([1, 2, 3, 4])

In [4]:
arr = np.array(lst, ndmin = 2)
arr

array([[1, 2, 3, 4]])

# 2. Arange Functions

##### The arange (start, stop, step, dtype = ): returns an array with evenly spaced elements as per the interval.
##### The interval mentioned is half-opened i.e. [start, stop]

In [5]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

# 3. Multidimensional array

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 4. Size Function

####In Python, numpy.size() function count the no. of elements along a given axis

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print('Total no. of elements in the array: ',arr.size)
print('Total no. of  rows: ',np.size(arr,0))   ## For rows
print('Total no. of  columns: ',np.size(arr,1))  ## For columns
print()
arr

Total no. of elements in the array:  12
Total no. of  rows:  4
Total no. of  columns:  3



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

#5. Shape Function

#### Shape of an array can be defined as the number of elements in each dimension. Dimension is the number of indices or subscripts, that we require in order to specify an individual element of an array

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])

print("Without shape function: ",(np.size(arr,0),np.size(arr,1)))

print("With shape function: ",arr.shape)


Without shape function:  (4, 3)
With shape function:  (4, 3)


#6. Dtype Function

In [9]:
arr1 = np.array([1,2,3,4])
arr1.dtype

dtype('int64')

# 7. Ndim function
#### np.ndarray.ndim() function return the no. of dimensions of an array

In [10]:
arr1 = np.array([1,2,3,1,2,3,4])
print(arr1.ndim)
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print(arr2.ndim)

arr3 = np.array(arr1, ndmin = 3)
print(arr3)

1
2
[[[1 2 3 1 2 3 4]]]


#8. Zeros Function

#### The numpy.zeros() function returns a new array of given shape and type, with zeros. Syntax:

#### numpy.zeros(shape, dtype = None)

In [11]:
arr = np.zeros(shape = (3,4), dtype = int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#9. Ones Function

#### The numpy.ones() function returns a new array of given shape and type, with ones. Syntax:

#### numpy.ones(shape, dtype = None)

In [12]:
arr = np.ones(shape = (3,4), dtype = int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 9. Eye Function
##### The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. The diagonal and 0's elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k.

In [13]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# 10. Empty Function
#### return an empty array of given shape and type

In [14]:
np.empty(shape = (5,5), dtype = int)

array([[      244570679,               0,               0,
                      0,               0],
       [              0,               0,               0,
                      0,               0],
       [              0,               0,               0,
                     97,       243619936],
       [132241225043248,               0,               0,
                      0,               0],
       [              0,               0,               0,
                      0,             368]])

# 11. Random Functions



### a) The numpy.random.rand() function creates an array of specified shape and fills it woth random values

In [15]:
np.random.rand(3,4)

array([[0.51986736, 0.99351272, 0.17536903, 0.03229527],
       [0.54336877, 0.79775816, 0.97596605, 0.31358025],
       [0.12762822, 0.45426416, 0.19480303, 0.14985823]])

### b) np.random.randint
is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills with random int from low(inclusive) to high(exclusive), i.e. in the interval

In [16]:
np.random.randint(low = 1,high = 6, size = 15)     # (start, end, no. of values to print)

array([5, 2, 1, 5, 1, 4, 4, 1, 2, 1, 2, 3, 5, 3, 3])

In [17]:
np.random.randint( 1, 6, 8)

array([3, 5, 5, 5, 1, 4, 4, 5])

### c) np.random.randn
The numpy.random.randn() function creates an array of specified shape and fills it with random number vaues as per *standard normal distribution*

In [18]:
np.random.randn(20)

array([ 0.45996264, -0.47197684,  0.38080649, -0.07603561, -1.55804991,
        0.3651151 , -0.53938041, -0.63673655,  0.31293122, -1.60253075,
       -1.170215  ,  0.006858  ,  0.48455647, -0.21090324, -0.75204058,
       -1.14704405,  1.8825931 ,  0.05315184,  1.77727571, -0.33917732])

In [19]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.hist(np.random.randn(100), bins = 15);


# 12. Reshape Function - will not alter the original data

The numpy.reshape() function shapes an array without changing the data of the array. *(It Should be noted that the product of the rows and columns should be same.)*

In [20]:
arr = np.random.randint(1, 15, (3,4))
print(arr)
print(arr.shape)
print(arr.reshape(4,3))
print(arr.reshape(6,2))

[[ 4  8  3  9]
 [ 9  6 13 10]
 [ 9  9  3 11]]
(3, 4)
[[ 4  8  3]
 [ 9  9  6]
 [13 10  9]
 [ 9  3 11]]
[[ 4  8]
 [ 3  9]
 [ 9  6]
 [13 10]
 [ 9  9]
 [ 3 11]]


# Linspace Function

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

Parameters:


* -> start: [Optional] start of Interval range, By default start = 0
* -> stop: end of interval range
* -> restep: If True, return (samples,step), By deafault restep = False
* -> num: [int, Optional] No. of Samples to generate
* -> dtype: type of Output array



In [21]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# 14. Flatten Function

ndarray.flatten() function return a copy of the array collapsed into on dimension

In [22]:
arr = np.random.randint(1, 15, (3,4))
print(arr.shape)
print(arr)
arr = arr.flatten()
print(arr)
print(arr.shape)


(3, 4)
[[10  7 14 13]
 [ 9  6  8  6]
 [ 1  3  6  6]]
[10  7 14 13  9  6  8  6  1  3  6  6]
(12,)


# 15. Logspace Function

The numpy.logspace() function returns number spaces eveny w.r.t interval on a log scale

Parameters:


* -> start: [float] start (base ** start) of interval range.
* -> stop: [float] end (base ** stop) of interval range
* -> endpoint: [Boolean, optional] If True, return (samples,step), By deafault restep = False
* -> num: [int, Optional] Base of log scale, By default equals 10.0
* -> dtype: type of Output array

In [24]:
np.logspace(2,4,10)

# to define the base of the log or log base

np.logspace(2,4,10, base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

# 16. Copy Function

In [27]:
arr1 = np.random.randint(1, 15,10)

arr2 = arr1

print(arr1, id(arr1))
print(arr2, id(arr2))

print('-'*50)

arr1 = np.random.randint(1, 15,10)

arr2 = arr1.copy()

print(arr1, id(arr1))
print(arr2, id(arr2))


[13  5 11  7  8  3  5 10  5  7] 132239674147152
[13  5 11  7  8  3  5 10  5  7] 132239674147152
--------------------------------------------------
[11  6 14 13  4 12 14 13 11 10] 132239674147536
[11  6 14 13  4 12 14 13 11 10] 132240923125072


#17. arr.max() , arr.min(), arr.sum() functions


In [29]:
arr = np.random.randint(1, 15, (3,4))
print(arr)
print('Max: ', arr.max())
print('Min: ', arr.min())
print('Sum: ', arr.sum())


[[ 9 13  2 14]
 [10 12 14 10]
 [14  4  4  4]]
Max:  14
Min:  2
Sum:  110
