In [2]:
import numpy as np

# 1. Converting a List into np Array

In [3]:
lst = [1,2,3,4]
print(type(lst))
arr = np.array(lst)
print(type(arr))
arr = np.array(lst, ndmin = 2)   #ndmin states how many dimensionsion we want in array
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3 4]]


In [4]:
arr = np.array(lst, ndmin = 1)   #ndmin states how many dimensionsion we want in array
arr

array([1, 2, 3, 4])

In [5]:
arr = np.array(lst, ndmin = 2)
arr

array([[1, 2, 3, 4]])

# 2. Arange Functions

##### The arange (start, stop, step, dtype = ): returns an array with evenly spaced elements as per the interval.
##### The interval mentioned is half-opened i.e. [start, stop]

In [6]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

# 3. Multidimensional array

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 4. Size Function

####In Python, numpy.size() function count the no. of elements along a given axis

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print('Total no. of elements in the array: ',arr.size)
print('Total no. of  rows: ',np.size(arr,0))   ## For rows
print('Total no. of  columns: ',np.size(arr,1))  ## For columns
print()
arr

Total no. of elements in the array:  12
Total no. of  rows:  4
Total no. of  columns:  3



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

#5. Shape Function

#### Shape of an array can be defined as the number of elements in each dimension. Dimension is the number of indices or subscripts, that we require in order to specify an individual element of an array

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])

print("Without shape function: ",(np.size(arr,0),np.size(arr,1)))

print("With shape function: ",arr.shape)


Without shape function:  (4, 3)
With shape function:  (4, 3)


#6. Dtype Function

In [10]:
arr1 = np.array([1,2,3,4])
arr1.dtype

dtype('int64')

# 7. Ndim function
#### np.ndarray.ndim() function return the no. of dimensions of an array

In [20]:
arr1 = np.array([1,2,3,1,2,3,4])
print(arr1.ndim)
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print(arr2.ndim)

arr3 = np.array(arr1, ndmin = 3)
print(arr3)

1
2
[[[1 2 3 1 2 3 4]]]


#8. Zeros Function

#### The numpy.zeros() function returns a new array of given shape and type, with zeros. Syntax:

#### numpy.zeros(shape, dtype = None)

In [24]:
arr = np.zeros(shape = (3,4), dtype = int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#9. Ones Function

#### The numpy.ones() function returns a new array of given shape and type, with ones. Syntax:

#### numpy.ones(shape, dtype = None)

In [25]:
arr = np.ones(shape = (3,4), dtype = int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 9. Eye Function
##### The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. The diagonal and 0's elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k.

In [29]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# 10. Empty Function
#### return an empty array of given shape and type

In [36]:
np.empty(shape = (5,5), dtype = int)

array([[   666232665,            0, 373662154839,  25769803780,
                   0],
       [           0,            0,            0,            0,
                   0],
       [           0,            0,            0,            0,
                   0],
       [           0,            0,            0,            0,
                   0],
       [           0,            0,            0,            0,
                 400]])

# 11. Random Functions



### a) The numpy.random.rand() function creates an array of specified shape and fills it woth random values

In [41]:
np.random.rand(3,4)

array([[0.96680462, 0.0399778 , 0.51288586, 0.83971115],
       [0.04019483, 0.30826964, 0.06991902, 0.88322685],
       [0.00919272, 0.2129271 , 0.27961519, 0.80377653]])

### b) np.random.randint
is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills with random int from low(inclusive) to high(exclusive), i.e. in the interval

In [48]:
np.random.randint(low = 1,high = 6, size = 15)     # (start, end, no. of values to print)

array([1, 3, 5, 5, 2, 1, 1, 5, 2, 2, 5, 2, 5, 4, 3])

In [49]:
np.random.randint( 1, 6, 8)

array([5, 1, 4, 2, 3, 3, 1, 4])