<a href="https://colab.research.google.com/github/Ainadri-Mandal/DS_Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [3]:
import numpy as np


In [4]:
lst = [[1,2,3],
       [1,2,3],
       [1,2,3]]

In [5]:
type(lst)

list

In [6]:
arr = np.array(lst)

In [7]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [8]:
type(arr) # ndarray means n-dimensional array

numpy.ndarray

In [9]:
arr.ndim #to get the dimensions of the array arr

2

In [10]:
arr.shape

(3, 3)

In [11]:
arr.size

9

In [12]:
arr.dtype

dtype('int64')

In [13]:
zeros = np.zeros((3,5))


In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zeros.dtype

dtype('float64')

In [16]:
ones = np.ones((6,3), dtype = int)

In [17]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Reshape & Random Number Generator

In [18]:
np.random.random()

0.4700857187451467

In [19]:
arr = np.random.random((3,3))

In [20]:
if np.random.random() > 0.5:
  print("Run the function")
else:
  print("Don't run the function")

Run the function


In [21]:
np.arange(1,10,2) #Acts like for loop range ( start, stop, steps)

array([1, 3, 5, 7, 9])

In [22]:
#np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)


In [23]:
np.linspace(1,10,6, dtype = int) # gives range of no.s (strt, stop, no. of values u want, dtype)

array([ 1,  2,  4,  6,  8, 10])

In [24]:
arr = np.random.random((4,3))

In [25]:
arr

array([[0.42137495, 0.04713399, 0.56919578],
       [0.38778905, 0.1883145 , 0.60323476],
       [0.49698278, 0.63501428, 0.82032849],
       [0.95864283, 0.58133232, 0.07853987]])

In [26]:
np.reshape(arr, (3,4))

array([[0.42137495, 0.04713399, 0.56919578, 0.38778905],
       [0.1883145 , 0.60323476, 0.49698278, 0.63501428],
       [0.82032849, 0.95864283, 0.58133232, 0.07853987]])

In [27]:
arr.flatten()

array([0.42137495, 0.04713399, 0.56919578, 0.38778905, 0.1883145 ,
       0.60323476, 0.49698278, 0.63501428, 0.82032849, 0.95864283,
       0.58133232, 0.07853987])

# Arithmetic operations on array

In [28]:
arr =np.array([1,2,3,4,5,6])


In [29]:
arr

array([1, 2, 3, 4, 5, 6])

In [30]:
print(arr + 1)
print(arr - 1)
print(arr * 8)
print(arr % 2)
print(arr / 2)
print(arr // 2)
print(arr ** 2)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 8 16 24 32 40 48]
[1 0 1 0 1 0]
[0.5 1.  1.5 2.  2.5 3. ]
[0 1 1 2 2 3]
[ 1  4  9 16 25 36]


In [31]:
arr *= 2

In [32]:
arr

array([ 2,  4,  6,  8, 10, 12])

In [33]:
print(arr.max())
print(int(arr.max()))
print(int(arr.min()))

12
12
2


In [34]:
arr = np.array([[1,4,7],
                [2,5,4],
                [3,6,3]])

In [35]:
arr

array([[1, 4, 7],
       [2, 5, 4],
       [3, 6, 3]])

In [36]:
arr.max(axis = 0)  # Gives max value column wise

array([3, 6, 7])

In [37]:
arr.min(axis = 0)

array([1, 4, 3])

In [38]:
arr.max(axis = 1) # Gives max value row wise

array([7, 5, 6])

In [39]:
arr.min(axis = 1)

array([1, 2, 3])

In [40]:
int(arr.sum())

35

# Arithmetic Operations on Multiple Arrays

In [41]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr2 = np.array([[9,8,7],
                [6,5,4],
                [3,2,1]])

In [42]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [43]:
arr1 * arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

## To perform the dot product

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [46]:
arr1.dot(arr2)  # Using the dot operator

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

# Accessing the elements of an array

In [47]:
arr = np.array([1,2,3,4,5])
print(arr[:])   # returns a full slice (i.e., all elements)
print(arr[:2])
print(arr[2:])
print(arr[2:-2])
print(arr[:-2])

[1 2 3 4 5]
[1 2]
[3 4 5]
[3]
[1 2 3]


In [48]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr1[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr1[ : , : 1] # for 2d array
          # first : is used for rows and 2nd : is used for columns

array([[1],
       [4],
       [7]])

In [55]:
arr1[:1,:]

array([[1, 2, 3]])

In [57]:
arr1[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr1[2:,:]

array([[7, 8, 9]])

In [60]:
arr1[:,2:]

array([[3],
       [6],
       [9]])

In [61]:
arr1[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [62]:
arr1[:,1:2]

array([[2],
       [5],
       [8]])

In [66]:
print("Printing the middle element of the matrix")
arr1[1:2,1:2]

Printing the middle element of the matrix


array([[5]])

# Arithmetic Operations on array

In [72]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

#Performing Arithmetic with two ways

print("Using + operator: ", a+b)
print("Using numpy add function", np.add(a,b))
print("\n")
print("Using - operator: ", a-b)
print("Using numpy subtract function", np.subtract(a,b))
print("\n")
print("Using * operator: ", a*b)
print("Using numpy multiply function", np.multiply(a,b))
print("\n")
print("Using / operator: ", a-b)
print("Using numpy divide function", np.divide(a,b))

Using + operator:  [  7  77  23 130]
Using numpy add function [  7  77  23 130]


Using - operator:  [ 3 67  3 70]
Using numpy subtract function [ 3 67  3 70]


Using * operator:  [  10  360  130 3000]
Using numpy multiply function [  10  360  130 3000]


Using / operator:  [ 3 67  3 70]
Using numpy divide function [ 2.5        14.4         1.3         3.33333333]
