<a href="https://colab.research.google.com/github/Ainadri-Mandal/DS_Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np


In [ ]:
lst = [[1,2,3],
       [1,2,3],
       [1,2,3]]

In [ ]:
type(lst)

list

In [ ]:
arr = np.array(lst)

In [ ]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
type(arr) # ndarray means n-dimensional array

numpy.ndarray

In [ ]:
arr.ndim #to get the dimensions of the array arr

2

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
zeros = np.zeros((3,5))


In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
ones = np.ones((6,3), dtype = int)

In [ ]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Reshape & Random Number Generator

In [ ]:
np.random.random()

0.24420954983424725

In [ ]:
arr = np.random.random((3,3))

In [ ]:
if np.random.random() > 0.5:
  print("Run the function")
else:
  print("Don't run the function")

Don't run the function


In [ ]:
np.arange(1,10,2) #Acts like for loop range ( start, stop, steps)

array([1, 3, 5, 7, 9])

In [ ]:
#np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)


In [ ]:
np.linspace(1,10,6, dtype = int) # gives range of no.s (strt, stop, no. of values u want, dtype)

array([ 1,  2,  4,  6,  8, 10])

In [ ]:
arr = np.random.random((4,3))

In [ ]:
arr

array([[0.60029253, 0.62577241, 0.34293518],
       [0.38602206, 0.01571501, 0.143015  ],
       [0.45865154, 0.52930022, 0.76323022],
       [0.6279162 , 0.82944189, 0.35053761]])

In [ ]:
np.reshape(arr, (3,4))

array([[0.60029253, 0.62577241, 0.34293518, 0.38602206],
       [0.01571501, 0.143015  , 0.45865154, 0.52930022],
       [0.76323022, 0.6279162 , 0.82944189, 0.35053761]])

In [ ]:
arr.flatten()

array([0.60029253, 0.62577241, 0.34293518, 0.38602206, 0.01571501,
       0.143015  , 0.45865154, 0.52930022, 0.76323022, 0.6279162 ,
       0.82944189, 0.35053761])

# Arithmetic operations on array

In [ ]:
arr =np.array([1,2,3,4,5,6])


In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(arr + 1)
print(arr - 1)
print(arr * 8)
print(arr % 2)
print(arr / 2)
print(arr // 2)
print(arr ** 2)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 8 16 24 32 40 48]
[1 0 1 0 1 0]
[0.5 1.  1.5 2.  2.5 3. ]
[0 1 1 2 2 3]
[ 1  4  9 16 25 36]


In [ ]:
arr *= 2

In [ ]:
arr

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
print(arr.max())
print(int(arr.max()))
print(int(arr.min()))

12
12
2


In [ ]:
arr = np.array([[1,4,7],
                [2,5,4],
                [3,6,3]])

In [ ]:
arr

array([[1, 4, 7],
       [2, 5, 4],
       [3, 6, 3]])

In [ ]:
arr.max(axis = 0)  # Gives max value column wise

array([3, 6, 7])

In [ ]:
arr.min(axis = 0)

array([1, 4, 3])

In [ ]:
arr.max(axis = 1) # Gives max value row wise

array([7, 5, 6])

In [ ]:
arr.min(axis = 1)

array([1, 2, 3])

In [ ]:
int(arr.sum())

35

# Arithmetic Operations on Multiple Arrays

In [ ]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr2 = np.array([[9,8,7],
                [6,5,4],
                [3,2,1]])

In [ ]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
arr1 * arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

## To perform the dot product

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
arr1.dot(arr2)  # Using the dot operator

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

# Accessing the elements of an array

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[:])   # returns a full slice (i.e., all elements)
print(arr[:2])
print(arr[2:])
print(arr[2:-2])
print(arr[:-2])

[1 2 3 4 5]
[1 2]
[3 4 5]
[3]
[1 2 3]


In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1[:,:] # for 2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
|